server:
  port: ${PORT:0}

kafka:
  bootstrap-server: localhost:9092

  producer:
    user-action-topic: stats.user-actions.v1
    properties:
      bootstrap.servers: ${kafka.bootstrap-server}
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: ru.practicum.collector.kafka.UserActionAvroSerializer
      linger.ms: 0 # время (в миллисекундах), которое продюсер ждет, прежде чем отправить накопленные сообщения.

grpc:
  server:
    port: ${GRPC_PORT:0}

  client:
    hub-router:
      address: 'discovery:///hub-router'