syntax = "proto3";

import "google/protobuf/timestamp.proto";

package stats.service.dashboard;  // имя пакета в мире gRPC/Protobuf - используется только в работе с gRPC, может не совпадать с пакетами java и с папками

option java_multiple_files = true; // генерирует каждый класс в отдельном файле (иначе все классы будут внутри одного родительского класса)
option java_package = "ru.practicum.recommendations.proto"; // можно указать, в какой пакет будут складываться сгенерированные классы.

message UserPredictionsRequestProto {
  int64  user_id = 1; // идентификатор пользователя, для которого вычисляются рекомендации;
  int32  max_results = 2; // ограничение количества мероприятий в результате выполнения запроса.
}

message SimilarEventsRequestProto {
  int64  event_id = 1; // идентификатор мероприятия, для которого нужно найти похожие мероприятия;
  int64  user_id = 2; // идентификатор пользователя, для которого из выдачи нужно исключить мероприятия, с которыми он уже взаимодействовал;
  int32  max_results = 3; // ограничение количества мероприятий в результате выполнения запроса.
}

message InteractionsCountRequestProto {
  repeated int64 event_ids = 1; // идентификаторы мероприятий, для которых нужно вернуть сумму всех взаимодействий.
}

message RecommendedEventProto {
  int64  event_id = 1; // идентификатор рекомендуемого мероприятия;
  double score = 2; // либо предсказанная оценка, либо коэффициент сходства, либо сумма весов действий с указанным мероприятием (в зависимости от метода, который вызывался в gRPC-сервисе).

}
