syntax = "proto3";

package stats.service.dashboard; // имя пакета в мире gRPC/Protobuf - используется только в работе с gRPC, может не совпадать с пакетами java и с папками

import "google/protobuf/empty.proto";
import "recommendations/messages/RecommendationsProto.proto";

option java_package = "ru.practicum.recommendations.proto"; // можно указать, в какой пакет будут складываться сгенерированные классы.
option java_outer_classname = "RecommendationsControllerProto";

service RecommendationsController {
  rpc GetRecommendationsForUser (UserPredictionsRequestProto)
      returns (stream RecommendedEventProto);

  rpc GetSimilarEvents (SimilarEventsRequestProto)
      returns (stream RecommendedEventProto);

  rpc GetInteractionsCount(InteractionsCountRequestProto)
      returns (stream RecommendedEventProto);
}